# Generated by Django 2.2.3 on 2019-07-27 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0002_auto_20190727_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='hospital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='med.Hospital', verbose_name='Больница'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='specialization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='med.Specialization', verbose_name='Специализация'),
            preserve_default=False,
        ),
    ]
