# Generated by Django 2.2.3 on 2019-07-27 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0003_auto_20190727_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='default_hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='med.Hospital', verbose_name='Больница по умолчанию'),
        ),
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Открыта'), (2, 'Ждет оценку'), (3, 'Закрыта'), (4, 'Отменена')], default=1, verbose_name='Статус'),
        ),
    ]
