# Generated by Django 2.2.3 on 2019-07-28 05:35

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0004_auto_20190727_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='specializations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='med.Specialization', verbose_name='Специализация'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('hospital', models.BooleanField(verbose_name='Вопрос о больнице')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='med.Specialization', verbose_name='Специализация')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
            managers=[
                ('random_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.BooleanField(blank=True, null=True, verbose_name='Ответ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='med.Question', verbose_name='Вопрос')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='med.Record', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Ответ на вопрос',
                'verbose_name_plural': 'Ответ на вопрос',
            },
        ),
    ]
