# Generated by Django 2.2.3 on 2019-07-28 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0005_auto_20190728_1035'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='question',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='record',
            name='rate',
        ),
        migrations.AddField(
            model_name='question',
            name='positive_answer',
            field=models.BooleanField(default=True, verbose_name='Положительный ответ'),
            preserve_default=False,
        ),
    ]
