# Generated by Django 2.2.3 on 2019-07-28 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0006_auto_20190728_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='med.Specialization', verbose_name='Специализация'),
        ),
    ]
