# Generated by Django 2.2.3 on 2019-07-28 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0007_auto_20190728_1150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Ответ на вопрос', 'verbose_name_plural': 'Ответы на вопросы'},
        ),
        migrations.RenameField(
            model_name='position',
            old_name='specializations',
            new_name='specialization',
        ),
    ]
